version: '3.8'

services:
  # Spark Master
  spark-master:
    build: ./Dockerfiles/spark
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_MODE=master

  # Spark Worker
  spark-worker:
    build: ./Dockerfiles/spark
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  # Kafka (Broker)
  kafka:
    build: ./Dockerfiles/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Zeppelin
  zeppelin:
    build: ./Dockerfiles/zeppelin
    container_name: zeppelin
    ports:
      - "8081:8080"
    depends_on:
      - spark-master
      - spark-worker

  # Airflow
  airflow:
    build: ./Dockerfiles/airflow
    container_name: airflow
    ports:
      - "8082:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags

  # Metabase
  metabase:
    build: ./Dockerfiles/metabase
    container_name: metabase
    ports:
      - "3000:3000"

  # MinIO
  minio:
    build: ./Dockerfiles/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password

networks:
  default:
    driver: bridge
